version: '3.3'

services:
  registry:
    image: registry:2
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - registry:/data
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.http.routers.${PROJECT}-http.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.${PROJECT}-http.entrypoints=http
        - traefik.http.routers.${PROJECT}-http.middlewares=https-redirect
        - traefik.http.routers.${PROJECT}-https.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.${PROJECT}-https.entrypoints=https
        - traefik.http.routers.${PROJECT}-https.tls=true
        - traefik.http.routers.${PROJECT}-https.tls.certresolver=le
        - traefik.http.services.${PROJECT}.loadbalancer.server.port=5000

volumes:
  registry: